### ISSUE TITLE
Add more information to readiness probes

### ISSUE THREAD

**Issue by embano1** [gravitational/workshop#17]
As discussed [here](https://github.com/kubernetes/kubernetes/issues/43576) sometimes it´s not only necessary to gracefully shutdown (your might also want to mention graceful shutdowns in the doc) but also to call a pre-stop lifecycle hook. 

Only this will ensure that the pod is being taken out of the service endpoint list **before** getting SIGTERM/ SIGKILL (depending on the termination policy). 

How to reproduce: Try to hammer the service during scale-in or rolling update with "go-wrk" or "hey" tools to see connections being dropped.

**Comment by klizhentas** [comment]
great idea, will add some examples of this, thanks for the feedback!

**Comment by embano1** [comment]
cool, thx!
see here for some code i used to demo:
https://github.com/kubernetes/ingress/issues/322#issuecomment-315470102
