### ISSUE TITLE
Update worker.yaml in k8s101 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/workshop#39]
Update worker.yaml (line 21) in mattermost directory in k8s101 workshop

Currently states:

`image: mattermost-worker:2.1.0`

Prefix image with registry for example: 

`image: $registry/mattermost-worker:2.1.0`

**Comment by UnderGreen** [comment]
@aelkugia it is fine. The magic happens during `tele build` or low level `gravity import` when image value is replaced with registry prefix.

**Comment by aelkugia** [comment]
@UnderGreen during the k8s101 training the training participants have not been introduced to gravity or tele build just yet. At this point we are just executing:

`$ kubectl create -f mattermost/worker.yaml --record`

**Comment by knisbet** [comment]
Would be nice to know if there is a cleaner way, ie if minikube configures the VM in a way where cluster names are reachable, then it could just be set to something like registry.default.svc.cluster.local. I don't know if that's feasible though.

**Comment by eldios** [comment]
there's a way depicted here https://developers.redhat.com/blog/2019/07/11/deploying-an-internal-container-registry-with-minikube-add-ons/

but I'm not sure if I want to consider that A LOT less hacky than just add a line in /etc/hosts manually or similra.

**Comment by eldios** [comment]
done.
